name: Build CI
on: [push, pull_request]
jobs:
  pocketmineBuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Build PHAR
        run: php -d phar.readonly=0 build.php
        working-directory: ./pocketmine-api
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PocketMine
          path: pocketmine-api/PocketMine-MP.phar
  pluginBuild:
    runs-on: ubuntu-latest
    needs: pocketmineBuild
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}
    steps:
      - uses: actions/checkout@v4
      - name: Download PocketMine api
        uses: actions/download-artifact@v4
        with:
          name: PocketMine
          path: pmnk-plugin/src/main/resources/pocketmine-api/
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          mvn install:install-file -Dfile=pmnk-plugin/libs/jphar-2.0.1.jar -DgroupId=name.npetrovski.jphar -DartifactId=jphar -Dversion=2.1.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true
          mvn -B package --file pmnk-plugin/pom.xml
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PM-NK
          path: pmnk-plugin/target/PMNK-0.1.0-PM-3.23.1.jar